### ISSUE TITLE
No license in the repository

### ISSUE THREAD

**Issue by MarcinGoreckiTTPSC** [vinzdeveloper/json-rule-editor#12]
Hi,

I would like to use this app in my project, but there's no license giving the permission. Would you consider setting one, please?

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by vinzdeveloper** [comment]
Hiya,

Thanks for notifying me. License has been updated.

https://github.com/vinzdeveloper/json-rule-editor/blob/master/LICENSE
