### ISSUE TITLE
Unable to install in Mxlinux

### ISSUE THREAD

**Issue by byteshiva** [vinzdeveloper/json-rule-editor#26]
Unable to install in Mxlinux, Does it requires any additional components or libraries.

**Comment by vinzdeveloper** [comment]
Hi @byteshiva 
Can you share any error logs or screenshot to understand better. Also are you able to install other packages in your Mxlinux?

**Comment by byteshiva** [comment]
You can find the log here: 
https://gist.github.com/byteshiva/7b493e41a2e66265ba0569f1fc782926

**Comment by vinzdeveloper** [comment]
Thanks for sharing the log. i could see you are using node 16 in your machine and looks node sass is not compatible with it.

https://github.com/sass/node-sass/issues/3077

You can either change the node sass version to latest in package json and re install or downgrade the node version and try npm install.

**Comment by byteshiva** [comment]
Still failing at log details.


https://gist.github.com/byteshiva/7b493e41a2e66265ba0569f1fc782926#gistcomment-3801394

I've upgraded 
package.json
```
    "node-sass": "6.0.1",

```

**Comment by vinzdeveloper** [comment]
Looks like sass-loader (webpack plugin) is not compatible with the latest node-sass 🙃. you have to upgrade sass-loader package as well!

Similar thread i just found out in node-sass page:

https://github.com/sass/node-sass/issues/3103

**Comment by byteshiva** [comment]
Still throwing error:
Details available at 
https://gist.github.com/byteshiva/7b493e41a2e66265ba0569f1fc782926#gistcomment-3801466

**Comment by vinzdeveloper** [comment]
I just got another thread related to new error you got. As many packages are linked together, we are facing new issues after solving one. its really annoying to upgrade each packages individually. We have to read the documentation to understand the prerequisites. I just have to analyse all the versions including node before upgrading the version in package.json.

https://github.com/webpack-contrib/sass-loader/issues/924

if you need to use it for time being, its in below url, so you can use it simply
https://json-rule-editor.com/

If not, you have to downgrade node js to 10 version to install from scratch.

**Comment by byteshiva** [comment]
Thanks,
I've downgraded nodejs to v12.0.0, and it works without any errors

Details
https://gist.github.com/byteshiva/7b493e41a2e66265ba0569f1fc782926

**Comment by vinzdeveloper** [comment]
Node-sass and node version compatibility issue. we have to upgrade all the inter dependent modules inline with the latest version. closing the issue at the moment.
