### ISSUE TITLE
about array type

### ISSUE THREAD

**Issue by MacleZhou** [vinzdeveloper/json-rule-editor#34]
May I have an example on 'array' type? 

for example, my fact model is a hierarchy model like case.lifes<Life>, I need the loop to check sub-attribute in each of the life under lifes(which is an list in case object), how can I do it?

**Comment by vinzdeveloper** [comment]
Hi @MacleZhou ,

you have an array and want to execute and see the outcome for each item in your array? - can you explain bit more to understand better?

Check out the Advanced example to manage dynamic facts from object

https://github.com/CacheControl/json-rules-engine

**Comment by vinzdeveloper** [comment]
Not reported over two months. so closing the issue
