### ISSUE TITLE
can not install the packages 

### ISSUE THREAD

**Issue by Gftakla** [vinzdeveloper/json-rule-editor#47]
Hi,

I git-cloned the solution to my computer and ran 'npm install' to get all packages, but NPM reported many deprecated packages and then erred out with the messages below. Also, no package was trapped and the node_modules folder was not created since those old packages need Python 2.7

I tried ncu to upgrade all packages, but the code does  not run and errs out

Does anyone have a safe way to upgrade the packages without breaking the code?

> npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated mini-create-react-context@0.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated redux-devtools-extension@2.13.8: Package moved to @redux-devtools/extension.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\...s\json-rule-editor\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\...\json-rule-editor\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\...\\json-rule-editor\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.17.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\gtakla\source\repos\json-rule-editor\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\...\json-rule-editor\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\...s\json-rule-editor\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\gtakla\source\repos\json-rule-editor\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\...\json-rule-editor\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\...\json-rule-editor\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\gtakla\source\repos\json-rule-editor\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\...\json-rule-editor\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\...\json-rule-editor\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\gtakla\source\repos\json-rule-editor\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\...\json-rule-editor\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\....\json-rule-editor\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\...\json-rule-editor\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\...\json-rule-editor\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\...\json-rule-editor\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\...\json-rule-editor\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\json-rule-editor\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\...\json-rule-editor\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...npm-cache\_logs\2022-10-20T16_17_09_149Z-debug-0.log

**Comment by vinzdeveloper** [comment]
Hi @Gftakla 

can you please install python 2 in your machine and try npm install?

**Comment by Gftakla** [comment]
Thank you!
I tried that, but got more pages of errors due to dependencies on old deprecated packages. 
I used ncu to update the packages (see below) and then ran yarn install to update all packages. 
building with new  packages create compilation Error: Compiling RuleSet failed: Query arguments on 'loader' has been removed in favor of the 'options' property (at ruleSet[1].rules[2].loader: url-loader?limit=10000&minetype=application/font-woff)       







> ncu -u
Using yarn
Upgrading C:\Users\gtakla\source\repos\json-rule-editor\package.json
[====================] 42/42 100%
 @babel/core                        7.7.7  →   7.19.6
 @babel/plugin-transform-runtime    7.9.6  →   7.19.6
 @babel/preset-env                  7.7.7  →   7.19.4
 @babel/preset-react                7.7.4  →   7.18.6
 @babel/runtime                     7.9.2  →   7.19.4
 @hot-loader/react-dom            16.13.0  →   17.0.2
 babel-loader                       8.0.6  →    8.2.5
 css-loader                         3.4.2  →    6.7.1
 eslint                             6.8.0  →   8.26.0
 eslint-plugin-react               7.18.0  →  7.31.10
 file-loader                        5.0.2  →    6.2.0
 history                           4.10.1  →    5.3.0
 html-webpack-plugin                3.2.0  →    5.5.0
 husky                              4.2.5  →    8.0.1
 json-rules-engine                  5.0.3  →    6.1.2
 lodash                           4.17.15  →  4.17.21
 mini-css-extract-plugin            0.9.0  →    2.6.1
 node-sass                          6.0.1  →    7.0.3
 postcss-loader                     3.0.0  →    7.0.1
 react                            16.12.0  →   18.2.0
 react-bootstrap-sweetalert         5.1.9  →    5.2.0
 react-d3-tree                     1.16.1  →    3.3.5
 react-dom                        16.12.0  →   18.2.0
 react-hot-loader                 4.12.20  →   4.13.0
 react-notifications                1.6.0  →    1.7.4
 react-redux                        7.1.3  →    8.0.4
 react-router-dom                   5.1.2  →    6.4.2
 react-spinners                     0.8.1  →   0.13.6
 redux                              4.0.5  →    4.2.0
 redux-thunk                        2.3.0  →    2.4.1
 sass-loader                       11.1.1  →   13.1.0
 style-loader                       1.1.2  →    3.3.1
 url-loader                         4.1.0  →    4.1.1
 webpack                           4.41.5  →   5.74.0
 webpack-cli                       3.3.10  →   4.10.0
 webpack-dev-server                3.10.1  →   4.11.1

**Comment by vinzdeveloper** [comment]
its not ideal to update all the packages in order to avoid few deprecated packages error. we may have to analyse which package throws error during compilation and has to sort out.

I see, json rule engine library is updated to 6.* from 5.* so does react from 16.* to 18.*

It is currently working as per dependency version covered in package.json. if you get error for the same version as per package.json file, please share the error, i will see to it. 

Meanwhile, if you want to use this tool, please launch www.json-rule-editor.com link to use it directly without any local installation.

**Comment by Gftakla** [comment]
Thank you for looking into it!
I agree that packages update is not the right path, but as I mentioned using the current packages kept erroring. 
I liked the online version and wanted to work on it. I may work on a solution for the packages and share it when I get time
