### ISSUE TITLE
Cannot edit decisions once created (eidt icon is not working)

### ISSUE THREAD

**Issue by mazharVenD** [vinzdeveloper/json-rule-editor#57]
Once a decision is created user can not edit it (clicking edit icon does nothing ) and user have to re add facts and conditions

**Comment by vinzdeveloper** [comment]
Hey,

After clicking edit icon, you have to select any of the nodes only then it allows you to edit that respective fact or add / amend.

As you see below, i have selected name fact and clicked remove button from above. 


<img width="1099" alt="image" src="https://user-images.githubusercontent.com/61467683/209876286-67b1805e-5cf5-4ff8-97f5-3e4964e04e5f.png">


<img width="1106" alt="image" src="https://user-images.githubusercontent.com/61467683/209876369-6dd1ed7a-b8e8-47ab-aa38-e80182579d15.png">

**Comment by vinzdeveloper** [comment]
And we cant edit the "name" fact (above example) from john to other name. only way is to remove the fact and add name fact again with new value.
