### ISSUE TITLE
Working with fact type object creates issue while validating

### ISSUE THREAD

**Issue by mazharVenD** [vinzdeveloper/json-rule-editor#58]
I have followed below link to create an employee advance step ruleset
https://vinzdeveloper.github.io/json-rule-editor/docs/advanced.html

![image](https://user-images.githubusercontent.com/121544274/209783625-bf77e2f7-8534-4cb3-b91e-9f072efe4a06.png)
 
 
 But it shows below error while validating:
 
 
![image](https://user-images.githubusercontent.com/121544274/209783798-616d0257-2b1e-49e2-a9e7-102bb6c96967.png)

**Comment by vinzdeveloper** [comment]
Yes we cant validate the path params in json rule editor, its restrictions from json-rule-engine actually (its mentioned in the documentation already). the purpose of having path params is to handle the value comes from api or other data objects actually. At the moment, its not handled in json rule editor. but i will think about it if there is anyway we can do it to validate this  kind of facts.
