### ISSUE TITLE
which license?  (LICENSE and package.json disagree)

### ISSUE THREAD

**Issue by risacher** [vinzdeveloper/json-rule-editor#64]
The LICENSE file is GPL, but the package.json says ISC.

**Comment by vinzdeveloper** [comment]
Thanks for letting me know. TBH, i didnt change the license in package json after its created. This is GPL. I dont want to put any restrictions for other users to make use of this user interface. If they need amendments, i dont have any concern to clone/fork the code and change the flavour as per their need.
