### ISSUE TITLE
Unable to use it

### ISSUE THREAD

**Issue by Kaucia** [vinzdeveloper/json-rule-editor#71]
The page is not loading after I click on Create button on the home page (http://localhost:8080/#/home)

**Comment by vinzdeveloper** [comment]
i will have a look. meanwhile, you can use http://json-rule-editor.com

**Comment by vinzdeveloper** [comment]
@Kaucia i reverted latest changes. can you pull now?

**Comment by Kaucia** [comment]
Thanks a lot
It's working
